### ISSUE TITLE
Fixes related to xugrid issues

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#213]
- [x] .sel(): https://github.com/Deltares/xugrid/issues/26 (sel issue)
- [x] .sel(): https://github.com/Deltares/xugrid/issues/30 (edges are not always correct)
- [x] .sel(): when done: Add where/sel ugrid example to mapfile notebook (sel currently fails, wait for xugrid fix+release)
- [x] .sel(): https://github.com/Deltares/xugrid/issues/41 (in xugrid main branch, so pre-release)
- [x] https://github.com/Deltares/xugrid/issues/27 (support for multiple dimensions plot via histogram?)
- [x] https://github.com/Deltares/xugrid/issues/25 (flexible dimnames?)
- [x] https://github.com/Deltares/xugrid/issues/39
- [x] https://github.com/Deltares/xugrid/issues/44
- [x] https://github.com/Deltares/xugrid/issues/43
- [x] https://github.com/Deltares/xugrid/issues/48
- [x] https://github.com/Deltares/xugrid/issues/49 (blocks removal of dfmt.plot_netmapdata())
- [x] https://github.com/Deltares/xugrid/issues/54
- [x] https://github.com/Deltares/xugrid/issues/61
- [x] https://github.com/Deltares/xugrid/issues/64
- [x] https://github.com/Deltares/xugrid/issues/68 (for westernscheldt model)
- [x] https://github.com/Deltares/xugrid/issues/67
- [x] https://github.com/Deltares/xugrid/issues/85
- [ ] https://github.com/Deltares/xugrid/issues/98
- [ ] https://github.com/Deltares/xugrid/issues/42
- [ ] https://github.com/Deltares/xugrid/issues/56
- [ ] https://github.com/Deltares/xugrid/issues/58
- [ ] https://github.com/Deltares/xugrid/issues/63 (for GTSM)
- [ ] https://github.com/Deltares/xugrid/issues/78
- [ ] https://github.com/Deltares/xugrid/issues/80
- [ ] https://github.com/Deltares/xugrid/issues/99
- [ ] https://github.com/Deltares/xugrid/issues/88
- [ ] https://github.com/Deltares/xugrid/issues/100

Related tasks:
- [ ] update xugrid dependency after xugrid release
- [x] Move from uda.rasterize() to uds.rasterize() after fix of https://github.com/Deltares/xugrid/issues/61
- [x] remove edgecolors argument from polycollection plots after fix of https://github.com/Deltares/xugrid/issues/64
- [ ] check/implement edge validator: https://github.com/Deltares/xugrid/issues/68#issuecomment-1509852706
- [ ] check if implementation corresponds to xugrid example: https://deltares.github.io/xugrid/examples/regridder_overview.html or wait for regridder update (https://github.com/Deltares/xugrid/issues/69)
- [ ] maybe `interpolate_na` is a good alternative for `bfill`/`ffill` for Delft3D4 regulargrid plots with nans in m,n-values: https://github.com/Deltares/xugrid/issues/70

Can be closed?:
- [x] https://github.com/Deltares/xugrid/issues/31 (plotting quiver on regridded dataset). New regridder available (https://github.com/Deltares/dfm_tools/issues/212), improve and (partly) move to xugrid?
- [ ] https://github.com/Deltares/xugrid/issues/59 (although it would be nice to have it in xugrid instead, discuss this and https://github.com/Deltares/dfm_tools/issues/206)
