### ISSUE TITLE
Fixes related to meshkernelpy issues

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#234]
- https://github.com/Deltares/MeshKernelPy/issues/29
- https://github.com/Deltares/MeshKernelPy/issues/30
- https://github.com/Deltares/MeshKernelPy/issues/31
- https://github.com/Deltares/MeshKernelPy/issues/32
- https://github.com/Deltares/MeshKernelPy/issues/33
- https://github.com/Deltares/MeshKernelPy/issues/34
- https://github.com/Deltares/MeshKernelPy/issues/35
- https://github.com/Deltares/dfm_tools/issues/217

Example script with these and some more issues: https://github.com/Deltares/dfm_tools/blob/main/tests/examples_workinprogress/workinprogress_meshkernel_creategrid.py

**Comment by veenstrajelmer** [comment]
Meshkernelpy release 2.1.0:
- [x] https://github.com/Deltares/MeshKernelPy/issues/39
- [x] https://github.com/Deltares/MeshKernelPy/issues/29
- [x] https://github.com/Deltares/MeshKernelPy/issues/34 (seems necessary to properly refine coastlines)
- [x] https://github.com/Deltares/MeshKernelPy/issues/69
- [x] https://github.com/Deltares/MeshKernelPy/issues/30
- [x] https://github.com/Deltares/MeshKernelPy/issues/33 (might be solved when actual spherical grid is possible)
- [x] https://github.com/Deltares/MeshKernelPy/issues/40
- [x] https://github.com/Deltares/MeshKernelPy/issues/54
- [x] solve main issues: https://github.com/Deltares/MeshKernelPy/issues/28
- [x] repair macOS support: https://github.com/Deltares/HYDROLIB-core/issues/444

Release 3.0.0:
- [x] https://github.com/Deltares/MeshKernelPy/issues/63
- [x] https://github.com/Deltares/MeshKernelPy/issues/32
- [x] https://github.com/Deltares/MeshKernelPy/issues/73
- [x] https://github.com/Deltares/MeshKernelPy/issues/76
- [x] https://github.com/Deltares/MeshKernelPy/issues/78
- [x] https://github.com/Deltares/MeshKernelPy/issues/81
- [x] https://github.com/Deltares/MeshKernelPy/issues/44
- [ ] https://github.com/Deltares/MeshKernelPy/issues/47
- [x] https://github.com/Deltares/MeshKernelPy/issues/102
- [x] compute grid? >> construct/make makes more sense
- [x] https://github.com/Deltares/MeshKernelPy/issues/103
- [x] `xugrid.ugrid.ugrid1d.Ugrid1d.meshkernel` and `xugrid.ugrid.ugrid2d.Ugrid2d.meshkernel` both call `mk.MeshKernel(is_geographic=False)` so that now fails
- [x] https://github.com/Deltares/dfm_tools/issues/550
- [x] https://github.com/Deltares/dfm_tools/issues/563

mk 4.1.0 (released 2024-02-15):
- [x] https://github.com/Deltares/MeshKernelPy/issues/113
- [x] https://github.com/Deltares/MeshKernelPy/issues/107
- [x] https://github.com/Deltares/MeshKernelPy/issues/108 >> exceptions upon wrong input
- [x] https://github.com/Deltares/MeshKernelPy/issues/102
- [x] https://github.com/Deltares/MeshKernelPy/issues/97
- [x] ridge refinement [GRIDEDIT-502](https://issuetracker.deltares.nl/browse/GRIDEDIT-502)
- [x] macos support: https://issuetracker.deltares.nl/browse/GRIDEDIT-796
- [x] https://github.com/Deltares/MeshKernelPy/issues/142
- [x] https://github.com/Deltares/MeshKernelPy/issues/145
- [x] https://github.com/Deltares/HYDROLIB-core/issues/612 >> convert to meshkernel issue or can we work around it?

Meshkernelpy 4.2.0:
- [x] https://github.com/Deltares/MeshKernelPy/issues/106 >> https://github.com/Deltares/meshkernelpy/pull/134
- [x] https://github.com/Deltares/MeshKernelPy/issues/146
- [x] https://github.com/Deltares/MeshKernelPy/issues/150
- [x] https://github.com/Deltares/MeshKernelPy/issues/172
- [x] https://github.com/Deltares/MeshKernelPy/issues/149
- [x] https://github.com/Deltares/MeshKernelPy/issues/162
- [x] https://github.com/Deltares/MeshKernelPy/issues/167
- [x] https://github.com/Deltares/MeshKernelPy/issues/151
- [x] https://github.com/Deltares/MeshKernelPy/issues/31
- [x] https://github.com/Deltares/dfm_tools/issues/860

meshkernel 5.0.1/5.0.2/6.0.0:
- [x] https://github.com/Deltares/MeshKernelPy/issues/152
- [x] https://github.com/Deltares/MeshKernelPy/issues/189
- [x] HYDROLIB-core broke with meshkernelpy 5.0.0: https://github.com/Deltares/HYDROLIB-core/issues/702

Release 8.1.2:
- [x] https://github.com/Deltares/MeshKernelPy/issues/217
- [x] https://github.com/Deltares/dfm_tools/issues/1078 >> https://github.com/Deltares/MeshKernelPy/issues/199 and https://github.com/Deltares/MeshKernelPy/issues/153 >> probably all resolved with fix described in https://github.com/Deltares/MeshKernelPy/issues/153#issuecomment-2876746905. >> update issue and example code (will not generate the same illegalcells because algorithm was updated.
- [x] https://github.com/Deltares/MeshKernelPy/issues/227
- [x] https://github.com/Deltares/MeshKernelPy/issues/228
- [x] https://github.com/Deltares/MeshKernelPy/issues/229
- [x] https://github.com/Deltares/MeshKernelPy/issues/96

Release 8.1.3:
- [x] https://github.com/Deltares/MeshKernelPy/issues/181
- [x] https://github.com/Deltares/MeshKernelPy/issues/234 >> https://github.com/Deltares/HYDROLIB-core/issues/927 >> https://github.com/Deltares/HYDROLIB/pull/195
- [x] https://github.com/Deltares/MeshKernelPy/issues/237
- [x] https://github.com/Deltares/dfm_tools/issues/1232
- [x] https://github.com/Deltares/MeshKernelPy/issues/195 >> https://github.com/Deltares/MeshKernelPy/pull/235

Meshkernelpy release 8.2.1:
- [x] restore macos support: https://github.com/Deltares/MeshKernel/pull/498
- [x] https://github.com/Deltares/MeshKernelPy/issues/242
- [x] update mkpy macos versions just like https://github.com/Deltares/MeshKernel/pull/501
- [x] https://github.com/Deltares/dfm_tools/issues/909#issuecomment-2265013735 (follow up of https://github.com/Deltares/MeshKernelPy/issues/150) >> https://issuetracker.deltares.nl/browse/GRIDEDIT-1795 >> https://github.com/Deltares/MeshKernel/pull/490 and https://github.com/Deltares/MeshKernelPy/pull/243 >> https://github.com/Deltares/MeshKernelPy/issues/247
- [x] public get-inner-bounds function: https://issuetracker.deltares.nl/browse/GRIDEDIT-2044

Meshkernelpy release 8.3.0:
- [x] https://github.com/Deltares/MeshKernel/pull/524 >> relates also to changes in the delft3dfm code in https://github.com/Deltares/Delft3D/pull/648 (DIMRset 2.30.24, 20 March 2026)
- [x] https://github.com/Deltares/MeshKernelPy/issues/265 >> gcc dependency was also added in HYDROLIB-core in https://github.com/Deltares/HYDROLIB-core/commit/f0dce07b8a71b1fbafcb245f86373b49fb6b8a14. HYDROLIB macos tests are still failing.
- [x] https://github.com/Deltares/MeshKernelPy/pull/264 >> https://github.com/Deltares/MeshKernelPy/pull/271 >> for bas2fm
