### ISSUE TITLE
Release fixed dependency versions after issues are solved

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#332]
- [x] release fixed `numpy` version after fixing https://github.com/Deltares/dfm_tools/issues/295
- [x] release fixed `xarray` version after fixing https://github.com/Deltares/xugrid/issues/78. Connected testcase: `test_opendataset_ugridplot()`.
- [x] release fixed  `pandas` version after https://github.com/Deltares/dfm_tools/issues/267. Connected testcase: `test_xarray_pandas_resample()`. This is an issue for py38 only, since it was solved in xarray 2023.3.0, but xarray 2023.1.0 is the latest py38 release. Alternatively, https://github.com/Deltares/dfm_tools/issues/507
- [x] https://github.com/Deltares/dfm_tools/issues/536
- [x] #557
