### ISSUE TITLE
Prepare 0.12.0 release

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#399]
Todo:
- [x] https://github.com/Deltares/dfm_tools/issues/400
- [x] https://github.com/Deltares/dfm_tools/issues/401
- [x] https://github.com/Deltares/dfm_tools/issues/411
- [x] https://github.com/Deltares/dfm_tools/issues/425
- [x] wait for xugrid release (https://github.com/Deltares/xugrid/issues/101 and https://github.com/Deltares/xugrid/issues/78) >> expected on 5 July
- [x] wait for meshkernelpy release (https://github.com/Deltares/MeshKernelPy/issues/29 and https://github.com/Deltares/MeshKernelPy/issues/34)
- [x] #428
- [x] install pip version of mkpy on VM
- [x] https://github.com/Deltares/dfm_tools/issues/421 (requires meshkernel>=2.1.0, so first merge main after updating requirements. Also update whats-new)
- [x] https://github.com/Deltares/dfm_tools/issues/383
- [x] https://github.com/Deltares/xugrid/issues/113
- [x] Mention modelbuilder/meshkernel functions in whatsnew, also add general introduction to each release. Eg xugrid in 0.11 and gives loads of possibilities like coorinate conversion, shapefile export, ugrid sel, regridding, rasterizing (link to ugrid docs)
- [x] fix whatsnew `pypipip` typo
- [x] https://github.com/Deltares/dfm_tools/issues/432
- [x] remove branches
- [x] run local testbank
- [x] add zenodo badge in readme (automatic new release?): https://zenodo.org/record/7857394
- [x] bumpversion to 0.12.0
- [x] make release
- [x] check if supported versions button now works
- [x] send newsletter

**Comment by veenstrajelmer** [comment]
v0.12.0 was released
