### ISSUE TITLE
Run Python 3.13 testbank

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#559]
First pre-release is available at the end of October according to https://peps.python.org/pep-0719/#schedule, final in October 2024:
- 3.13.0 beta 1: Wednesday, 2024-05-08 (No new features beyond this point.)
- 3.13.0 beta 2: Wednesday, 2024-06-05
- 3.13.0 beta 3: Thursday, 2024-06-27
- now (4-7-2024)
- 3.13.0 beta 4: Tuesday, 2024-07-16
- 3.13.0 candidate 1: Tuesday, 2024-07-30
- 3.13.0 candidate 2: Tuesday, 2024-09-03
- 3.13.0 final: Tuesday, 2024-10-01

Github available versions: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Testbank fails because of:
- [x] ERROR: No matching distribution found for numpy>=2.0.0.dev0: https://github.com/numpy/numpy/issues/24318 and https://github.com/numpy/numpy/issues/25917 >> numpy will support python 3.13 approximately from may 2024 >> https://github.com/numpy/numpy/issues/26157
- [x] retried on 1-5-2024, now failing on scipy with `  ../scipy/meson.build:163:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake` >> https://github.com/scipy/scipy/issues/20669 >> was not an issue anymore later even though issue is not closed yet
- [x] pandas 2.2.3 can be installed on py3.13 on windows, all older versions raise errors
- [x] copernicusmarine requires zarr which requires numcodecs which does not yet support py3.13: https://github.com/zarr-developers/zarr-python/issues/2317 and https://github.com/zarr-developers/numcodecs/issues/593
- [x] https://github.com/pydata/bottleneck/issues/459
- [x] https://github.com/ecmwf/multiurl/issues/14#issuecomment-2401171216
- [x] cdsapi added py313 tests in https://github.com/ecmwf/cdsapi/pull/126
- [x] https://github.com/Deltares/ddlpy/issues/118
- [x] upon installation of netCDF4: `ValueError: did not find HDF5 headers` >> https://github.com/Unidata/netcdf4-python/issues/1370 >> netcdf4 1.7.2 supports python 3.9 to 3.13 and numpy v2 >> no python 3.13 wheels for windows >> were added 1 day later
- [x] https://github.com/python/cpython/issues/125235 >> will be fixed in python 3.13.1 (December 2024)
- [x] https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/158 (will be fixed in copernicusmarine 2.0.0, December 2024, so also fix https://github.com/Deltares/dfm_tools/issues/933)
- [x] xugrid requires numba: https://github.com/numba/numba/issues/9413 >> https://github.com/numba/llvmlite/issues/1084 >> https://github.com/numba/numba/issues/9777
- [x] hydrolib-core 0.8.0 enforces lxml<5 which does not support py313 >> https://github.com/Deltares/HYDROLIB-core/issues/707 >> await release after 9 jan 2025
- [x] check meshkernel: https://github.com/Deltares/MeshKernelPy/issues/190 >> properly installs, also succeeds tests?
- [x] and probably more >> nope, this is it!

If py3.13 testbank is green:
- [x] add to general pytest workflow file (runs on every PR and merge)
- [x] remove dedicated py313 workflow file
- [x] add py3.13 to supported versions in pyproject.toml
- [x] updated readme/installation/contributing docs

For future reference: https://scientific-python.org/specs/spec-0000/

**Comment by rgommers** [comment]
Hi, I noticed this from an incoming link on a scipy issue. I just wanted to point out that there are numpy and scipy nightlies at https://anaconda.org/scientific-python-nightly-wheels/numpy/ and https://anaconda.org/scientific-python-nightly-wheels/scipy/. You should use those if you want 3.13 support without having to build from source. And never build releases from PyPI for a future Python version; build from `main` instead if you do choose to build from source.

**Comment by veenstrajelmer** [comment]
Hi @rgommers thanks for the heads up. I read something like that indeed, but I am not in a hurry. This issue is just meant to track the development of Python 3.13 support of the dfm_tools dependencies. Every now and then I run the testbank to see if it can already install all dependencies or not (with released versions). Once it can install without issues, I will check if all tests pass and then add 3.13 to the supported versions in the pyproject.toml.
