### ISSUE TITLE
DSD installation guide

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#585]
**Installation guide**

For two of the breakout sessions of the Delft3D user days [day 1](https://softwaredays.deltares.nl/nl/-/delft3d-user-days-2023-day-1) (breakout 1) and [day 2](https://softwaredays.deltares.nl/nl/-/delft3d-user-days-2023-day-2) (breakout 2) we will do some hands-on work with Python. The below installation guide provides you with a Python environment called `dsd_env` that contains the packages `dfm_tools`, `hydromt_delft3dfm`, `HYDROLIB-core` and `xugrid` (and all their dependencies). With this environment you can run all the example notebooks provided for two breakout sessions day1-breakout1 and day2-breakout2.

Installation of Python environment:
- required for day1-breakout1 and day2-breakout2
- download and install Anaconda from [anaconda.com](https://www.anaconda.com)
- open Anaconda prompt
- `conda create --name dsd_env python=3.11 git -c conda-forge -y` (python 3.9 or 3.10 are also fine)
- `conda activate dsd_env`
- `pip install hydromt_delft3dfm[examples] dfm_tools`
- download and unzip the course materials in `dsd_delft3d_python_coursematerials.zip`. This will result in 4 subfolders with course materials from 4 GitHub repositories. Depending on the breakout session you will use one or more of these subfolders
- launch jupyter with: `jupyter notebook`
- open the notebook you want to work in and run it with SHIFT+ENTER or press the play button in the toolbar above

Register to retrieve CDS and CMEMS data:
- required for day1-breakout1
- We will make use of publicly available data from Copernicus Programme of the European Union. To access this data you need to make two accounts at [Copernicus Marine Service](https://data.marine.copernicus.eu/register) and the [Climate Data Store](https://cds.climate.copernicus.eu/user/register).
- do not forget to accept the license agreements
- you will be prompted for the CMEMS credentials and CDS apikey by the 2D3D modelbuilder notebook

Installation of DeltaShell (Delft3D-FM GUI):
- optional for day1-breakout1, required for day2-breakout1
- If you want to run a model during day1-breakout1, you require an FM executable. This is conveniently shipped with the DeltaShell GUI. The Deltashell GUI is required in day2-breakout1.
- provided via [...]

Installation of OET for MATLAB:
- optional for day1-breakout1
- if you use MATLAB, you can also do the post-processing of FM models (day1-breakout1) with MATLAB. For this you require `EHY_tools` available via OpenEarthTools (OET)
- download and install tortoise SVN from https://tortoisesvn.net/
- checkout OET from https://svn.oss.deltares.nl/repos/openearthtools/trunk/matlab, more info in [slide 19 of how_to_use_subversion.pps](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fpublicwiki.deltares.nl%2Fdownload%2Fattachments%2F42401943%2Fhow_to_use_subversion.pps&wdOrigin=BROWSELINK)
- add to matlab path

**Course material links**

You can also find all course materials online:
- hydromt_delft3dfm notebooks and example data: https://github.com/Deltares/hydromt_delft3dfm/tree/main/examples (day1-breakout1)
- dfm_tools notebooks: https://github.com/Deltares/dfm_tools/blob/main/docs/notebooks (day1-breakout1)
- HYDROLIB-core notebooks: https://github.com/Deltares/HYDROLIB-core/tree/main/docs/tutorials/dsd_2022_demo (day2-breakout2)
- xugrid notebooks: https://deltares.github.io/xugrid/user_guide.html (day2-breakout2)

**Download course materials from github**

```
mkdir dsd_delft3d_python_coursematerials
cd dsd_delft3d_python_coursematerials
curl https://codeload.github.com/deltares/hydromt_delft3dfm/tar.gz/main | tar -xz --strip=1 hydromt_delft3dfm-main/examples
ren examples hydromt_delft3dfm
curl https://codeload.github.com/deltares/dfm_tools/tar.gz/main | tar -xz --strip=2 dfm_tools-main/docs/notebooks
ren notebooks dfm_tools
curl https://codeload.github.com/deltares/HYDROLIB-core/tar.gz/main | tar -xz --strip=3 HYDROLIB-core-main/docs/tutorials/dsd_2022_demo
ren dsd_2022_demo HYDROLIB-core
curl https://codeload.github.com/deltares/xugrid/tar.gz/main | tar -xz --strip=1 xugrid-main/examples
ren examples xugrid
jupytext --to notebook xugrid\*.py
```

**TODO**
- maybe zip all course material and send to participants, part is collected here: `p:\d-hydro\educations\Delft3D-FM 1D2D\Courses_2023\Nov_DSD_int\breakoutsession-hydromt-delft3dfm` (includes hydromt_delft3dfm pptx, hydromt_delft3dfm notebooks+data). We could add dfm_tools notebooks (or provide url in pptx for where to download them), maybe more
- move to n:\Teams\DSD\DSD-INT - Delft Software Days 2023\1.2 Delft3D User Days\Break-out sessions\1. Modelbuilding and postprocessing
- provide FM executable

Check this environment with:
- [x] dfm_tools testbank (unittests and systemtests)
- [x] hydromt_delft3dfm testbank
- [x] hydromt_delft3dfm example notebooks
