### ISSUE TITLE
Consider 12-hour offset for CMEMS data

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#878]
The functions `copernicusmarine.subset()` and `copernicusmarine.open_dataset()` always return start-of-interval time samples (e.g. start of hour, day, month, year) because of the underlying ARCO format. Native datasets (retrieved with `copernicusmarine.get()` or with opendap before December 2023) use a mix of start-of-interval and center-of-interval. We had mid-day timestamps when using opendap, now we have midnight values, but the actual data is the same. This is documented in https://help.marine.copernicus.eu/en/articles/8656000-differences-between-netcdf-and-arco-formats. In dfm_tools the copernicus opendap server was used to retrieve data until approximately December 2023 (so noon timestamps, center-of-interval). After that ([v0.18.0](https://github.com/Deltares/dfm_tools/releases/tag/v0.18.0) onwards), the copernicusmarine toolbox was used (so midnight timestamps, start-of interval).

Most of the datasets we use are daily means, so consider to correct for this by adding an offset of 12 hours. Frequently used datasets are documented in `dfmt.copernicusmarine_get_dataset_id()`. 
https://github.com/Deltares/dfm_tools/blob/03cabed8174f33a857823510aacb536531a7c8df/dfm_tools/download.py#L252-L287

The PUM states the daily averaged products are centered at noon, not at midnight, this issue restores this behaviour:
![Image](https://github.com/user-attachments/assets/58287278-4c82-4886-9b0b-95eddc570722)

Some usecases:
- downloading data and interpolate to boundaries to serve as boundary conditions for models, in this case it could make sense to move the daily average to noon, since this is then representative for the entire day and in the middle.
- when using the data as validation data for a model, it would be best to compare to daily averages of the model also. With xarray this would most probably end up at midnight also, so no timeshift is desired. When comparing to instantaneous model values, it is slightly more convenient to have the cmems data on midday, but it does not matter much and comparing a daily mean to an instantaneous value on midnight or noon is not accurate anyway.

Check performance and behaviour (like file names and extents) with:
```python
import dfm_tools as dfmt

# spatial extents
lon_min, lon_max, lat_min, lat_max = 12.5, 16.5, 34.5, 37

# time extents
date_min = '2015-11-01'
# date_max = '2020-07-31'
date_max = '2015-11-02'

dataset_id = 'cmems_mod_glo_phy_my_0.083deg_P1D-m' # daily means, corrected
dataset_id = 'cmems_mod_glo_phy_my_0.083deg_P1M-m' # monthly means, not corrected, intermediate days are also downloaded as empty files in case of freq="D"
# dataset_id = 'med-cmcc-cur-rean-d' # daily means, corrected
freq = "Y"
# freq = "M"
# freq = "D"

varkey_dict = {'cmems_mod_glo_phy_my_0.083deg_P1D-m':'uo',
               'cmems_mod_glo_phy_my_0.083deg_P1M-m':'so',
               'med-cmcc-cur-rean-d':'vo'}

dfmt.download_CMEMS(varkey=varkey_dict[dataset_id],
                    longitude_min=lon_min, longitude_max=lon_max, latitude_min=lat_min, latitude_max=lat_max,
                    date_min=date_min, date_max=date_max, freq=freq,
                    dir_output=".", overwrite=True, dataset_id=dataset_id)


# import xarray as xr; ds = xr.open_dataset(r"c:\DATA\checkouts\dfm_tools\tests\uo_2015.nc"); print(ds.time)
```

Todo:
- [x] https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/271
- [x] also consider https://github.com/Deltares/dfm_tools/issues/797 and https://github.com/Deltares/dfm_tools/issues/780
- [x] prevent floor/ceil in `dfmt.cmems_nc_to_ini()`: https://github.com/Deltares/dfm_tools/issues/1086
- [x] check writing of initial fields again, still two values around the model start time?
- [x] UPDATE 23-1-2025 after meeting with cmc devs: work around for now, metadata might be added later, cmc argument is not expected because of complexity
- [x] prevent floor/ceil in `dfmt.cmems_nc_to_bc()` (should not be needed anymore after #1062, but test with different start/stop times)
- [x] add testcase for `dfmt.cmems_nc_to_bc()`
- [x] re-introduce timeshift function including test from https://github.com/Deltares/dfm_tools/pull/392/files >> not needed since we now use `_ds_sel_time_outside()` that includes a test
- [x] beware on time administration, especially since date timestrings like "2020-06-29" are parsed to datetimes of the midnight version of that, while with normal `xr.Dataset.sel()` this would include the entire day. Also check if we can download end of reanalysis and start of reanalysis-interim smoothly. >> old notes, not so relevant anymore
- [x] check performance with code in download cmems test and code in https://github.com/Deltares/dfm_tools/issues/1033
- [x] check filenames and contents of downloaded files, also add tests
- [x] offset for monthly means? >> I guess not, since PUM does not state the original data is centered mid-month
- [x] when defining offset, not only check dataset string "P1D-m" but also check if the current times are indeed at midnight (or check in a test at least). >> not all daily monthly means have "P1D-m" in dataset_id, so maybe hardcode offset?
- [x] add 12 hour offset upon opening dataset (also when retrieving start/stoptimes from dataset). Could be done with corrected tstart/tstop or by opening with offset and subsetting after that. The latter is simpler, but requires outer time bound selection (with `_ds_sel_time_outside()` newly implemented in https://github.com/Deltares/dfm_tools/pull/1062), but could be slower than the default `outside` coordinate selection of `copernicusmarine`. Choose either of both, but check performance.
- [x] fix github test (passes locally on windows)
- [x] check codecov
- [x] test local modelbuilder
- [x] update notebook
- [x] remove redundant testcase to save pytest time
- [x] expected times for anfc testcase are probably incorrect when running test before noon, check this
- [x] add hardcoded 12-hour offset for "rean-d" also for [med datasets](https://data.marine.copernicus.eu/product/MEDSEA_MULTIYEAR_PHY_006_004/services) >> will be removed again in https://github.com/Deltares/dfm_tools/issues/1090
- [x] print/log dataset_id
- [ ] notify all users who downloaded cmems data in the last years, since midnight and noon datasets are not compatible. Good to redownload anyway since the spatial extents might also have slightly changed.
- [ ] test modelbuilder on EDITO datalab (has clean downloads)

The new implementation:
- downloads required timerange (outside buffered) in files per day/month/year
- all files are called to the period, so "2020" for "Y", "2020-11" for "M" and "2020-11-06" for "D". The 12 hour timestamp is not visible in the filenames.
- so monthly files of 1nov to 2nov 2020 for daily means at noon (corrected) would result in one "2020-10" file with 1 timestep (31oct 12:00) and one "2020-11" file with 2 timesteps (1nov 12:00 and 2 nov 12:00)
- when downloading monthly means with daily freq (or yearly with monthly/daily freq), empty files are created, this was also the case before. This can be avoided by downloading monthly means with monthly or yearly freq, easy as that.
- Currently, only daily means are corrected with an offset. The yearly/monthly/hourly/3hourly/6hourly averaged datasets are not corrected.
- [some products](https://data.marine.copernicus.eu/product/MEDSEA_MULTIYEAR_PHY_006_004/services) have datasets that have names not according to the convention. A daily mean dataset called `*rean-d` is also corrected with 12 hours. This is temporary hardcoding that will be removed in https://github.com/Deltares/dfm_tools/issues/1090.

**Alternative approach**
Alternatively, request a argument for `copernicusmarine.open_dataset()` to get averaged values in mid-time or start-time of the average. That would completely solve all complexity around this issue. Also request attributes, at the moment it is not clear in the dataset that the time is not instantaneous but averaged. Check if insitu timeseries are instantaneous and not averaged. Requested new argument and/or metadata via servicedesk.cmems@mercator-ocean.eu on 10-7-2024, the request is registered under ticket `[MDSOP-179]` and https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/271.

Potential projects: BES>>Malta, EDITO
