### ISSUE TITLE
Improve `dfmt.interp_uds_to_plipoints()`

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#911]
Useful to directly convert CMCC curvigrid (read as ugrid) to forcingmodel/bcfile, instead of first regridding to CMEMS raster. Example code shows that there are still several manual changes required before we can convert the interpolated dataset to a bc-file:
```python
import dfm_tools as dfmt
import hydrolib.core.dflowfm as hcdfm

# read plifile as gdf
pli = r'P:\11209133-ultfarms\02-Simulations\North_Sea_runs_Loreta\pre-processing\offshore_boundaries\FuMA_scripts\DCSM-FM_OB_all_20181108.pli' # polygon containing open boundary forcing points
pli_obj = hcdfm.PolyFile(pli)
pli_gdf = dfmt.PolyFile_to_geodataframe_points(pli_obj)

# only take first points to speed up for testing
pli_gdf_test = pli_gdf.iloc[:4]

scen = 'historical' # test
yr = 2005#, 2006, 2007, 2008] # test
datavar = 'so' # test

orgfile = fr'P:\archivedprojects\11206304-futuremares-rawdata-preps\data\CMIP6_BC\CMCC-ESM2\{datavar}_Omon_CMCC-ESM2_{scen}_r1i1p1f1_gn_199001-200912.nc'

nco = dfmt.open_dataset_curvilinear(orgfile, convert_360to180=True)
nco = nco.ugrid.to_nonperiodic(xmax=180)

# convert noleap to gregorian: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
time_units = nco['time'].encoding['units']
nco['time'] = nco.indexes['time'].to_datetimeindex()

# plot
# nco.so.isel(time=0, lev=0).ugrid.plot()

# subset in time to speed up for testing
nco_sel = nco.isel(time=slice(None,5))

# interpolate to points of polyfile
ds_points = dfmt.interp_uds_to_plipoints(uds=nco_sel, gdf=pli_gdf_test)

# TODO: manual edits that should not (all) be necessary
ds_points['time'].encoding['units'] = time_units # avoid empty time encoding units, not supported by dfmt.plipointsDataset_to_ForcingModel
ds_points = ds_points.rename({"lev":"z"}) # rename depth variable to expected value
ds_points_onevar = ds_points[["so"]] #only provide one quantity
ds_points_onevar["station_id"] = ds_points_onevar["node"] # station_id is required

# convert to bc/forcing hydrolib-core object
bc_points = dfmt.plipointsDataset_to_ForcingModel(ds_points_onevar)

# save to bc file
bc_points.save("test_file.bc")
```

Also:
- [x] https://github.com/Deltares/dfm_tools/issues/912
- [x] add `station_id` variable to dataset returned by `dfmt.interp_uds_to_plipoints()`
- [ ] fix https://github.com/Deltares/xugrid/issues/100

After fixing #912 the conversion_dict can also be applied and there are some additional improvements to the bc files possible (like depth correction and quantity renaming):
```python
import dfm_tools as dfmt
import hydrolib.core.dflowfm as hcdfm

# read plifile as gdf
pli = r'P:\11209133-ultfarms\02-Simulations\North_Sea_runs_Loreta\pre-processing\offshore_boundaries\FuMA_scripts\DCSM-FM_OB_all_20181108.pli' # polygon containing open boundary forcing points
pli_obj = hcdfm.PolyFile(pli)
pli_gdf = dfmt.PolyFile_to_geodataframe_points(pli_obj)

# only take first points to speed up for testing
pli_gdf_test = pli_gdf.iloc[:4]

scen = 'historical' # test
yr = 2005#, 2006, 2007, 2008] # test
quantity = 'salinitybnd' # test

conversion_dict = dfmt.get_conversion_dict()
ncvarname = conversion_dict[quantity]['ncvarname']

orgfile = fr'P:\archivedprojects\11206304-futuremares-rawdata-preps\data\CMIP6_BC\CMCC-ESM2\{ncvarname}_Omon_CMCC-ESM2_{scen}_r1i1p1f1_gn_199001-200912.nc'

nco = dfmt.open_dataset_curvilinear(orgfile, convert_360to180=True)
nco = nco.ugrid.to_nonperiodic(xmax=180)

# subset in time to speed up for testing
nco_sel = nco.isel(time=slice(None,5))

# apply conventions and conversions
# TODO: consider avoiding the need to use private functions
nco_conv = dfmt.interpolate_grid2bnd.ds_apply_conventions(nco_sel)
nco_conv = dfmt.interpolate_grid2bnd.ds_apply_conversion_dict(nco_conv, conversion_dict=conversion_dict, quantity_list=[quantity])

# plot
nco_conv[quantity].isel(time=0, z=0).ugrid.plot()

# interpolate to points of polyfile
ds_points = dfmt.interp_uds_to_plipoints(uds=nco_conv, gdf=pli_gdf_test)

ds_points_onevar = ds_points[[quantity]] #only provide one quantity
# TODO: station_id is required, consider renaming in interp_uds_to_plipoints already
ds_points_onevar["station_id"] = ds_points_onevar["node"]

# convert to bc/forcing hydrolib-core object
bc_points = dfmt.plipointsDataset_to_ForcingModel(ds_points_onevar)

# save to bc file
bc_points.save("test_file.bc")
```
