### ISSUE TITLE
investigate memory usage by `remove_ghost=True` in `dfmt.open_partitioned_dataset()`

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#957]
When opening 256 partitions with the default settings for `dfmt.open_partitioned_dataset()`, we get an overflow of the memory. To narrow it down to xugrid-only, we can set `remove_edges=False` and `remove_ghost=False`. Particularly `remove_ghost=True` seems to consume much memory. This kind of makes sense since we read the entire `da_domainno` variable per partition. But would be great if this could be resolved.

A bit of code for testing:
```python
import os
import glob
import dfm_tools as dfmt

dir_model = r"p:\11210284-011-nose-c-cycling\runs_fine_grid\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\DFM_OUTPUT_DCSM-FM_0_5nm_waq"
file_nc_pat = os.path.join(dir_model, "DCSM-FM_0_5nm_waq_0*_map.nc")
file_nc_list_all = glob.glob(file_nc_pat)
file_nc_list = file_nc_list_all[:20]

# chunks = {"time":1} # temporarily fails with valueerror on merged.chunks
chunks = "auto"

uds = dfmt.open_partitioned_dataset(file_nc_list, chunks=chunks, remove_edges=True, remove_ghost=True)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 113.71 sec
# >> xu.merge_partitions() with 10 partition(s): 33.18 sec
# >> dfmt.open_partitioned_dataset() total: 146.89 sec
# memory with 20 partitions: 21% to 32/35%

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks=chunks, remove_edges=False, remove_ghost=True)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 90.24 sec
# >> xu.merge_partitions() with 10 partition(s): 34.92 sec
# >> dfmt.open_partitioned_dataset() total: 125.16 sec
# memory with 20 partitions: 21% to 32?/35%

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks=chunks, remove_edges=True, remove_ghost=False)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 90.24 sec
# >> xu.merge_partitions() with 10 partition(s): 34.92 sec
# >> dfmt.open_partitioned_dataset() total: 125.16 sec
# memory with 20 partitions: 21% to ??/33%

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks=chunks, remove_edges=False, remove_ghost=False)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 64.82 sec
# >> xu.merge_partitions() with 10 partition(s): 33.47 sec
# >> dfmt.open_partitioned_dataset() total: 98.30 sec
# memory with 20 partitions: 21% to ??/33%
```

The above test are for 20/40 partitions, for all partitions we know:
 - all tests were done on a 32GB VM
 - when we read all 256 partitions with the defaults (`remove_edges=True` and `remove_ghost=True`), memory will overflow
 - when we read all 256 partitions with `remove_edges=False` and `remove_ghost=False`, 76% of the memory will be consumed after merging (or 76% of additional memory?)
 - `remove_ghost=True` consumes 2% more memory for 20 partitions, so this is >20% more memory for all 256 partitions

Follow-up test (tested with xugrid 0.11.2, so after implementation of single merged ugrid chunks and after fix for inconsistent chunks). This shows the same (a bit more memory usage with `remove_ghost=True`) and the chunks make no difference in memory/timings (but they do impact memory/timings significantly when retrieving single timesteps: https://github.com/Deltares/dfm_tools/issues/953):
```python
import os
import glob
import dfm_tools as dfmt

dir_model = r"p:\11210284-011-nose-c-cycling\runs_fine_grid\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\DFM_OUTPUT_DCSM-FM_0_5nm_waq"
file_nc_pat = os.path.join(dir_model, "DCSM-FM_0_5nm_waq_0*_map.nc")
file_nc_list_all = glob.glob(file_nc_pat)
file_nc_list = file_nc_list_all[:10]

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks="auto", remove_ghost=True)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 155.04 sec
# >> xu.merge_partitions() with 10 partition(s): 34.30 sec
# >> dfmt.open_partitioned_dataset() total: 189.34 sec
# memory with 10 partitions: 26% to 31/33%

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks="auto", remove_ghost=False)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 130.15 sec
# >> xu.merge_partitions() with 10 partition(s): 33.26 sec
# >> dfmt.open_partitioned_dataset() total: 163.41 sec
# memory with 10 partitions: 26% to ??/32%

# uds = dfmt.open_partitioned_dataset(file_nc_list, chunks={"time":1}, remove_ghost=True)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 150.64 sec
# >> xu.merge_partitions() with 10 partition(s): 33.55 sec
# >> dfmt.open_partitioned_dataset() total: 184.20 sec
# memory with 10 partitions: 26% to 31/33%

uds = dfmt.open_partitioned_dataset(file_nc_list, chunks={"time":1}, remove_ghost=False)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 129.42 sec
# >> xu.merge_partitions() with 10 partition(s): 35.63 sec
# >> dfmt.open_partitioned_dataset() total: 165.06 sec
# memory with 10 partitions: 26% to 30/32%
```

Todo:
 - [x] setting `remove_edges=False` is also attractive since validating the connectivity takes quite some time (>20 sec for 10 partitions). Was set as new default in https://github.com/Deltares/dfm_tools/issues/959
 - [x] `chunks = {"time":1}` fails temporarily with newest xugrid release (0.11.1), fixed by https://github.com/Deltares/xugrid/pull/279 >> https://github.com/Deltares/dfm_tools/issues/953
 - [x] add timings/memoryusage to this issue without changing `remove_edges`, but with changing chunks
 - [x] What is also noteworthy is that `xu.open_dataset()` takes significanly less time when passing the preprocess function (instead of dropping the vars on the `uds`), this shows that `xu.core.wrap.UgridDataset()` is also significantly slower with many variables. >> https://github.com/Deltares/xugrid/issues/285

update 19-8-2024:
`xu.merge_partitions()` mainly takes quite some time because there are many variables. When removing most of the variables before merging the required amount of time and memory is significantly reduced. However, it is important to not remove any of the grid/layer/topology variables. This is easiest with a preprocess function:
```python
import os
import glob
import dfm_tools as dfmt

dir_model = r"p:\11210284-011-nose-c-cycling\runs_fine_grid\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\DFM_OUTPUT_DCSM-FM_0_5nm_waq"
file_nc_pat = os.path.join(dir_model, "DCSM-FM_0_5nm_waq_0*_map.nc")
file_nc_list_all = glob.glob(file_nc_pat)
file_nc_list = file_nc_list_all[:10]

def drop_vars(ds):
    drop_var_list = []
    # add all water quality stat variables to the drop_var_list
    for varn in ds.data_vars:
        if varn.startswith("mesh2d_water_quality"):
            drop_var_list.append(varn)
    # remove again the ones you are interested in
    keep_var_list = ["mesh2d_water_quality_stat_1387"]
    for varn in keep_var_list:
        drop_var_list.remove(varn)
    ds = ds.drop_vars(drop_var_list)
    return ds

uds = dfmt.open_partitioned_dataset(file_nc_list, chunks="auto", remove_ghost=False, preprocess=drop_vars)
# >> xu.open_dataset() with 10 partition(s): 1 2 3 4 5 6 7 8 9 10 : 38.80 sec
# >> xu.merge_partitions() with 10 partition(s): 0.78 sec
# >> dfmt.open_partitioned_dataset() total: 39.58 sec
# memory with 10 partitions: 28% to 31%
```

**Comment by veenstrajelmer** [comment]
When using latest dfm_tools and xugrid releases, several optimizations are included (https://github.com/Deltares/xugrid/issues/285 and https://github.com/Deltares/dfm_tools/issues/968)


```python
import os
import glob
from time import sleep
import dfm_tools as dfmt
import datetime as dt

dir_model = r"p:\11210284-011-nose-c-cycling\runs_fine_grid\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\B05_waq_2012_PCO2_ChlC_NPCratios_DenWat_stats_2023.01\DFM_OUTPUT_DCSM-FM_0_5nm_waq"
file_nc_pat = os.path.join(dir_model, "DCSM-FM_0_5nm_waq_0*_map.nc")
file_nc_list_all = glob.glob(file_nc_pat)
file_nc_list = file_nc_list_all[:5]

uds = dfmt.open_partitioned_dataset(file_nc_list, remove_ghost=False) #, engine="h5netcdf")

print('>> plot single timestep: ',end='')
dtstart = dt.datetime.now()
uds["mesh2d_tureps1"].isel(time=-1, mesh2d_nInterfaces=-2).ugrid.plot()
print(f'{(dt.datetime.now()-dtstart).total_seconds():.2f} sec')
sleep(2)
```
